pub mod actions;
pub mod book;
pub mod citation;
pub mod folder;
pub mod identifiers;
pub mod library;
pub mod library_map;
pub mod manifest;
pub mod open_access;
pub mod publication;
pub mod tag;
pub mod user_profile;

pub use actions::*;
pub use book::*;
pub use citation::*;
pub use folder::*;
pub use identifiers::*;
pub use library::*;
pub use library_map::*;
pub use manifest::*;
pub use open_access::*;
pub use publication::*;
pub use tag::*;
pub use user_profile::*;

pub type BookId = uuid::Uuid;
pub type FolderId = uuid::Uuid;
pub type TagId = uuid::Uuid;
pub type UserId = uuid::Uuid;
pub type LibraryId = uuid::Uuid;
pub type CitationId = uuid::Uuid;
pub type ActionId = uuid::Uuid;
